# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "lib/private_strategy"
class Kanban < Formula
  desc ""
  homepage ""
  version "0.0.19"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/KatsuyaAkasaka/kanban/releases/download/v0.0.19/kanban_Darwin_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "1b648bf211a7edfd7166ae5f83cd3b35ae6af19b354474104bba87ef2a0c8fe6"

      def install
        bin.install "kanban"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/KatsuyaAkasaka/kanban/releases/download/v0.0.19/kanban_Darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "30f977d57ebbfe336a5918044e7b97a1f3b779df16cb2dab334f2ca55e1af66a"

      def install
        bin.install "kanban"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/KatsuyaAkasaka/kanban/releases/download/v0.0.19/kanban_Linux_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "8dd5aca6e5eb904e3a9fd3537f701a78763214a6d522946e785bda68e2b172bd"

        def install
          bin.install "kanban"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/KatsuyaAkasaka/kanban/releases/download/v0.0.19/kanban_Linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
        sha256 "1b60ab186172490d4157ffcaf3288e62078fc008157070aec81aeb6d88b64767"

        def install
          bin.install "kanban"
        end
      end
    end
  end
end
