# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kanban < Formula
  desc ""
  homepage ""
  version "0.0.14"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/KatsuyaAkasaka/kanban/releases/download/v0.0.14/kanban_Darwin_x86_64.tar.gz"
      sha256 "fad6c5860b6964f3b190a98c76d94ff60ec06c8577cab63f88663e5c5fef6be5"

      def install
        bin.install "kanban"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/KatsuyaAkasaka/kanban/releases/download/v0.0.14/kanban_Darwin_arm64.tar.gz"
      sha256 "bf432ba5497c26e4b26cd945911fd081b4423d1d24951ead3d41a08553c9957f"

      def install
        bin.install "kanban"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/KatsuyaAkasaka/kanban/releases/download/v0.0.14/kanban_Linux_x86_64.tar.gz"
        sha256 "37f765f33c0bef5f15675f52d503749cf9733b8da29e1074044cc76dc025ddb2"

        def install
          bin.install "kanban"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/KatsuyaAkasaka/kanban/releases/download/v0.0.14/kanban_Linux_arm64.tar.gz"
        sha256 "3b391fdf417057c8bba8e1aa1358cef62a0f550c53ab9e3de9e780cf061b10e2"

        def install
          bin.install "kanban"
        end
      end
    end
  end
end
