# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NoteCli < Formula
  desc "note-cli"
  homepage "https://github.com/KatsuyaAkasaka"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/KatsuyaAkasaka/note-cli/releases/download/v0.1.1/note-cli_0.1.1_Darwin_arm64.tar.gz"
      sha256 "78fd76c101c3b573c5bd46654666f670000695dfe83770f29e76e989871d87a3"

      def install
        bin.install "note-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/KatsuyaAkasaka/note-cli/releases/download/v0.1.1/note-cli_0.1.1_Darwin_x86_64.tar.gz"
      sha256 "0f2528f22859c3ed5db327aadda6fedcd8618af6048a003c9ddb753f04ddfd5b"

      def install
        bin.install "note-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/KatsuyaAkasaka/note-cli/releases/download/v0.1.1/note-cli_0.1.1_Linux_x86_64.tar.gz"
      sha256 "25c5e4f2779964f267bdea2e4073dc91f24134062135e9e3acaf46fc41e111dd"

      def install
        bin.install "note-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/KatsuyaAkasaka/note-cli/releases/download/v0.1.1/note-cli_0.1.1_Linux_arm64.tar.gz"
      sha256 "1eff6ae4e0a5caa9169f31e1b03f5354dfbc654f3116b532e9fd21a262271e14"

      def install
        bin.install "note-cli"
      end
    end
  end
end
