# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class NoteCli < Formula
  desc "note-cli"
  homepage "https://github.com/KatsuyaAkasaka"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/KatsuyaAkasaka/note-cli/releases/download/v0.1.0/note-cli_0.1.0_Darwin_arm64.tar.gz"
      sha256 "642e7ba3cee4bff14c136d0a8695a8d206a8e505daeb9541188d44c839da07fe"

      def install
        bin.install "note-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/KatsuyaAkasaka/note-cli/releases/download/v0.1.0/note-cli_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "63ee02259c466f3f4fbdda70011273383f93732847da5fc442ac917de55c7e95"

      def install
        bin.install "note-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/KatsuyaAkasaka/note-cli/releases/download/v0.1.0/note-cli_0.1.0_Linux_arm64.tar.gz"
      sha256 "0c25ebcb25236b6485939f29a7be351dee53aec372451f66f1027359b8a90ff0"

      def install
        bin.install "note-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/KatsuyaAkasaka/note-cli/releases/download/v0.1.0/note-cli_0.1.0_Linux_x86_64.tar.gz"
      sha256 "214fc3bf7a7f0987b3eadbbb4dd67de2c408ced711a5ccd196b8f2b6f423bf38"

      def install
        bin.install "note-cli"
      end
    end
  end
end
